export const fonts = {
  S28_Bold: {
    fontFamily: 'SpoqaNeoBold',
    fontSize: '28px',
    fontWeight: '700',
    lineHeight: '1.3',
  },
  S28_Regular: {
    fontFamily: 'SpoqaNeoRegular',
    fontSize: '28px',
    fontWeight: '400',
    lineHeight: '1.3',
  },
  S28_Light: {
    fontFamily: 'SpoqaNeoLight',
    fontSize: '28px',
    fontWeight: '300',
    lineHeight: '1.3',
  },
  S24_Bold: {
    fontFamily: 'SpoqaNeoBold',
    fontSize: '24px',
    fontWeight: '700',
    lineHeight: '1.3',
  },
  S24_Regular: {
    fontFamily: 'SpoqaNeoRegular',
    fontSize: '24px',
    fontWeight: '400',
    lineHeight: '1.3',
  },
  S20_Bold: {
    fontFamily: 'SpoqaNeoBold',
    fontSize: '20px',
    fontWeight: '700',
    lineHeight: '1.3',
  },
  S20_Regular: {
    fontFamily: 'SpoqaNeoRegular',
    fontSize: '20px',
    fontWeight: '400',
    lineHeight: '1.3',
  },
  S18_Bold: {
    fontFamily: 'SpoqaNeoBold',
    fontSize: '18px',
    fontWeight: '700',
    lineHeight: '1.3',
  },
  S18_Regular: {
    fontFamily: 'SpoqaNeoRegular',
    fontSize: '18px',
    fontWeight: '400',
    lineHeight: '1.3',
  },
  S16_Bold: {
    fontFamily: 'SpoqaNeoBold',
    fontSize: '16px',
    fontWeight: '700',
    lineHeight: '1.3',
  },
  S16_Regular: {
    fontFamily: 'SpoqaNeoRegular',
    fontSize: '16px',
    fontWeight: '400',
    lineHeight: '1.3',
  },
  S14_Bold: {
    fontFamily: 'SpoqaNeoBold',
    fontSize: '14px',
    fontWeight: '700',
    lineHeight: '1.3',
  },
  S14_Regular: {
    fontFamily: 'SpoqaNeoRegular',
    fontSize: '14px',
    fontWeight: '400',
    lineHeight: '1.3',
  },
  S12_Bold: {
    fontFamily: 'SpoqaNeoBold',
    fontSize: '12px',
    fontWeight: '700',
    lineHeight: '1.3',
  },
  S12_Regular: {
    fontFamily: 'SpoqaNeoRegular',
    fontSize: '12px',
    fontWeight: '400',
    lineHeight: '1.3',
  },
  S10_Bold: {
    fontFamily: 'SpoqaNeoBold',
    fontSize: '10px',
    fontWeight: '700',
    lineHeight: '1.3',
  },
  S10_Regular: {
    fontFamily: 'SpoqaNeoRegular',
    fontSize: '10px',
    fontWeight: '400',
    lineHeight: '1.3',
  },
}
